# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: test

variables:
  JAVA_HOME: 'C:\java\jdk-17'
  JAVA_HOME_11_X64: 'C:\java\jdk-17'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\java\jdk-17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'