apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-pipeline-demo-green
  namespace: default
  labels:
    app: java-pipeline-demo
    slot: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-pipeline-demo
      slot: green
  template:
    metadata:
      labels:
        app: java-pipeline-demo
        slot: green
        tags.datadoghq.com/service: java-pipeline-demo
        tags.datadoghq.com/env: production
        tags.datadoghq.com/version: "green"
    spec:
      initContainers:
        - name: dd-agent-init
          image: datadog/dd-lib-java-init:latest
          command: ["sh", "-c", "cp /datadog-init/package/dd-java-agent.jar /dd-agent"]
          volumeMounts:
            - name: dd-agent-volume
              mountPath: /dd-agent
      containers:
        - name: java-pipeline-demo
          image: madhumurundiacr.azurecr.io/java-pipeline-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: dd-agent-volume
              mountPath: /dd-agent
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_SERVICE
              value: "java-pipeline-demo"
            - name: DD_ENV
              value: "production"
            - name: DD_VERSION
              value: "green"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/dd-agent/dd-java-agent.jar"
      volumes:
        - name: dd-agent-volume
          emptyDir: {}
