apiVersion: v1
kind: Service
metadata:
  name: java-pipeline-demo-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: java-pipeline-demo
  ports:
  - port: 80
    targetPort: 8080
